#+TITLE: Doom Emacs config

Emacs config, requires [[https://github.com/hlissner/doom-emacs][Doom Emacs]].

This config is written as an org file ([[./config.el][config.el]]) and auto-compiles to [[./config.el][config.el]] using the ":config literate" option in [[./init.el][init.el]].

* Startup
#+begin_src elisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Make emacs maximized one startup
;; Might be useful in the future: https://christiantietze.de/posts/2021/06/emacs-center-window-on-current-monitor/
(add-hook 'doom-init-ui-hook 'toggle-frame-maximized)

#+end_src
* Navigation
** Visual line mode everywhere
Use global-visual-line-mode by default so that jk does not go up/down based on logical lines. Taken from [[https://emacs.stackexchange.com/questions/33360/how-to-open-org-files-with-visual-line-mode-automatically-turned-on][stackexchange]]. The goal here is to get vim-like behaviour of `nnoremap j gj` and `nnoremap k gk` in emacs.
#+begin_src elisp
(add-hook 'after-init-hook 'global-visual-line-mode)
#+end_src
** Line numbers
#+begin_src elisp
;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
;; (setq display-line-numbers-type 'nil)
#+end_src
** Prevent "jk" from exiting insert mode
#+begin_src elisp
(setq evil-escape-key-sequence nil)
#+end_src
** Window management
Switch to the new window after splitting
#+begin_src elisp
(setq evil-split-window-below t
      evil-vsplit-window-right t)

#+end_src

Fullscreen/maximized mode toggle
#+begin_src elisp
(bind-key "C-c F" 'toggle-frame-maximized)
#+end_src

Kill buffer and window
#+begin_src elisp
;; C-c c will contain all buffer-related bindings
(global-set-key (kbd "C-c b") 'my/buffer)

(defalias 'my/buffer
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "k") 'kill-buffer-and-window)
    map) "Buffer-related bindings")
#+end_src

** Files/folders
This code block contains generality for "C-c f" as a "files" binding but it's currently not needed. Might come in handy later though.
#+begin_src elisp
;; "C-c f" for files/folders
;; (global-set-key (kbd "C-c f") 'my/files)

;; (defalias 'my/files
;;   (let ((map (make-sparse-keymap)))
;;     (define-key map (kbd "t") 'my/treemacs)
;;     map) "Files-related bindings")
#+end_src
*** Treemacs
#+begin_src elisp
(global-set-key (kbd "C-c t") 'my/treemacs)

(defalias 'my/treemacs
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "t") 'treemacs) ;; Toggle treemacs
    (define-key map (kbd "a") 'treemacs-add-project-to-workspace)
    (define-key map (kbd "r") 'treemacs-remove-project-from-workspace)
    map) "Treemacs-related bindings")
#+end_src

* Mode-specific custom keybindings
Denote "C-c m" my/<localleader>, following Doom's naming of "SPC m".
#+begin_src elisp
(global-set-key (kbd "C-c m") 'my/<localleader>)
#+end_src
** Coding
*** Python
#+begin_src elisp
(defun my/bind-python-keys ()
  (defalias 'my/<localleader>
    (let ((map (make-sparse-keymap)))
      ;; REPL
      (define-key map (kbd "R") #'run-python)
      ;; Restart python
      (define-key map (kbd "r") #'pyvenv-restart-python)
      ;; Virtual environment
      (define-key map (kbd "v") #'pyvenv-activate)
      ;; Format
      (define-key map (kbd "f") #'python-black-buffer)
      map)))

(add-hook 'python-mode-hook 'my/bind-python-keys)
;; (add-hook 'python-mode-hook 'python-black-on-save-mode)
#+end_src

** Writing
*** TeX
#+begin_src elisp
(defun my/latexmk ()
  (interactive)
  (TeX-command "LatexMk" #'TeX-master-file nil))

(defun my/bibtex ()
  (interactive)
  (TeX-command "BibTeX" #'TeX-master-file nil))

(defun my/latex-view ()
    (interactive)
  (TeX-command "View" #'TeX-master-file nil))

(defun my/bind-latex-keys ()
  (defalias 'my/<localleader>
    (let ((map (make-sparse-keymap)))
      ;; Compile
      (define-key map (kbd "c") #'my/latexmk)
      ;; Recompile BibTeX
      (define-key map (kbd "b") #'my/bibtex)
      ;; Word count
      (define-key map (kbd "w") #'tex-count-words)
      map)))

(add-hook 'LaTeX-mode-hook 'my/bind-latex-keys)
#+end_src
* Coding
** Python
Make LSP ignore virtual environments which satisfy the pattern "venv_*"
#+begin_src elisp
(defun my/python-lsp-ignore-venv ()
  (add-to-list 'lsp-file-watch-ignored "[/\\\\]\\venv_*"))
(add-hook 'python-mode-hook
          '(lambda () (add-hook 'lsp-mode-hook 'my/python-lsp-ignore-venv)))


#+end_src

Search for any virtual environments with pattern "venv_*" and if there's a unique match, automatically activate it.
#+begin_src elisp
(defun my/venv_pattern ()
  "User-customizable virtual environment pattern"
  "venv_*")

(defun my/get-matching-project-root-files (regexp)
  "Find all root directories/files that begin with `regexp`"
  (seq-filter
   (lambda (x) (equal 0 (string-match-p regexp x)))
   (directory-files (projectile-project-root))))

(defun my/python-venv-auto-activate ()
  "Activate the virtual environment satisfying the pattern given by the function, my/venv_pattern if it's a unique match, otherwise do nothing"
  (interactive)
  (setq matching-venvs (my/get-matching-project-root-files (my/venv_pattern)))
  ;; If there's a unique match, set the venv. Otherwise, do nothing
  (when (equal (length matching-venvs) 1)
    (pyvenv-activate (concat (projectile-project-root) (car matching-venvs)))))

(add-hook 'python-mode-hook 'my/python-venv-auto-activate)
#+end_src

* LaTeX
Format environment and LatexMk on save
#+begin_src elisp

(defun my/latex-format-environment-on-save ()
  (add-hook 'after-save-hook #'LaTeX-fill-environment))

(defun my/latexmk-on-save ()
  "Run LatexMk after saving .tex files"
  (add-hook 'after-save-hook 'my/latexmk))

(add-hook 'LaTeX-mode-hook 'my/latexmk-on-save)
#+end_src


#+begin_src elisp
;; Make default latex viewer pdf-tools
;; (setq +latex-viewers '(pdf-tools))

;; Use pdf-tools to open PDF files
(setq TeX-view-program-selection '((output-pdf "PDF Tools"))
      TeX-source-correlate-start-server t)

;; Update PDF buffers after successful LaTeX runs
(add-hook 'TeX-after-compilation-finished-functions
          #'TeX-revert-document-buffer)

;; Make AUCTeX ask for main tex file in multi-document structure
(setq-default TeX-master nil)

;; Prevent AUCTeX from inserting braces automatically
(setq TeX-electric-sub-and-superscript nil)
#+end_src

* Org-mode

This directory allows syncing with beorg on iOS. Pretty cool!
#+begin_src elisp
(setq
 org-directory
 "~/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/")
#+end_src

Define a function for quickly opening up a file in the org directory
#+begin_src elisp
(defun my/open-org-directory ()
  (interactive) (ido-find-file-in-dir org-directory))

(global-set-key (kbd "C-c o") 'my/open-org-directory)
#+end_src

Make the first level org heading a little larger.
#+begin_src elisp
(custom-set-faces '(org-level-1 ((t (:inherit outline-1 :height 1.2)))))
#+end_src

Enable org-download so that we can drag and drop screenshots into org.
#+begin_src elisp
(require 'org-download)
(add-hook 'dired-mode-hook 'org-download-enable)
#+end_src

Use custom todo keywords and colours.
#+begin_src elisp
(after! org
  (setq org-todo-keywords
        '((sequence "TODO(t)" "IN-PROGRESS(p)" "WAITING(w)"
                    "IDEA(i)" "|" "DONE" "CANCELLED(c)"))))

;; Set other todo colors according to the nord theme (https://www.nordtheme.com/)
(setq org-todo-keyword-faces
      '(("IN-PROGRESS" . "#88C0D0")
        ("WAITING" . "#5E81AC")
        ("IDEA" . "#EBCB8B")
        ("CANCELED" . "#BF616A"))
      )

(setq org-log-done 'time)
#+end_src
* Shells
#+begin_src elisp
;; C-c s will contain all shell-related commands
(global-set-key (kbd "C-c s") 'my/shells)

(defalias 'my/shells
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "s") 'shell)
    (define-key map (kbd "e") 'eshell)
    (define-key map (kbd "t") 'term)
    (define-key map (kbd "v") 'vterm)
    map) "Shell-related bindings")
#+end_src
* Config management
Opening config.org, config.el, init.el, and packages.el uses "C-c e <char>" with <char> replaced by c, C, i, or p, respectively.
#+begin_src elisp

(defun my/goto-private-config-org-file ()
  "Open your private config.org file."
  (interactive)
  (find-file (expand-file-name "config.org" doom-private-dir)))

(defun my/goto-private-config-file ()
  "Open your private config.el file."
  (interactive)
  (find-file (expand-file-name "config.el" doom-private-dir)))

(defun my/goto-private-init-file ()
  "Open your private init.el file."
  (interactive)
  (find-file (expand-file-name "init.el" doom-private-dir)))

(defun my/goto-private-packages-file ()
  "Open your private packages.el file."
  (interactive)
  (find-file (expand-file-name "packages.el" doom-private-dir)))

;; C-c c will contain all config-related stuff
(global-set-key (kbd "C-c e") 'my/emacs-config)

(defalias 'my/emacs-config
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "c") #'my/goto-private-config-org-file)
    (define-key map (kbd "C") #'my/goto-private-config-file)
    (define-key map (kbd "i") #'my/goto-private-init-file)
    (define-key map (kbd "p") #'my/goto-private-packages-file)
    map) "Config-related bindings")
#+end_src
* Fonts
#+begin_src elisp
;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))
(setq doom-font (font-spec :family "Fira Mono" :size 15))
(setq doom-variable-pitch-font (font-spec :family "Fira Mono" :size 15))
(setq +zen-text-scale 0.25)
#+end_src
* Theme
#+begin_src elisp
;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-nord)
#+end_src
* Misc
#+begin_src elisp

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "Ian Waudby-Smith"
      user-mail-address "iwaudbysmith@gmail.com")

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
#+end_src
** Autocomplete/company
#+begin_src elisp
;; Make autocomplete less clunky: https://github.com/hlissner/doom-emacs/issues/77
;; (require 'company)
;; (setq company-idle-delay 0.2
;;       company-minimum-prefix-length 4)
#+end_src

