#+TITLE: Doom Emacs config

Emacs config, requires [[https://github.com/hlissner/doom-emacs][Doom Emacs]].

This config is written as an org file ([[./config.el][config.el]]) and auto-compiles to [[./config.el][config.el]] using the ":config literate" option in [[./init.el][init.el]].

* General
** Window size on startup
Set initial frame size and position
Largely based on https://christiantietze.de/posts/2021/06/emacs-center-window-on-current-monitor/ and https://www.reddit.com/r/emacs/comments/9c0a4d/tip_setting_initial_frame_size_and_position/
#+begin_src elisp

(defun my/set-initial-frame-size ()
  "Set the initial frame size to something reasonable. Works on multiple monitors"
  (interactive)
  (let* ((base-factor 0.93)
         (monitor-w (nth 2 (frame-monitor-workarea (selected-frame))))
         (monitor-h (nth 3 (frame-monitor-workarea (selected-frame))))
         (a-width (* monitor-w base-factor))
         (a-height (* monitor-h base-factor)))
    (set-frame-size (selected-frame)
                    (truncate a-width)
                    (truncate a-height) t)))

(defun my/frame-recenter (&optional frame)
  "Center FRAME on the screen.
FRAME can be a frame name, a terminal name, or a frame.
If FRAME is omitted or nil, use currently selected frame."
  (interactive)
  (unless (eq 'maximised (frame-parameter nil 'fullscreen))
    (let* ((frame (or (and (boundp 'frame)
                           frame)
                      (selected-frame)))
           (frame-w (frame-pixel-width frame))
           (frame-h (frame-pixel-height frame))
           ;; frame-monitor-workarea returns (x y width height) for the monitor
           (monitor-w (nth 2 (frame-monitor-workarea frame)))
           (monitor-h (nth 3 (frame-monitor-workarea frame)))
           (center (list (/ (- monitor-w frame-w) 2)
                         (/ (- monitor-h frame-h) 2))))
      (apply 'set-frame-position (flatten-list (list frame center))))))

(defun my/set-initial-frame ()
  (interactive)
  (my/set-initial-frame-size)
  (my/frame-recenter))

(setq frame-resize-pixelwise t)
(add-hook 'window-setup-hook #'my/set-initial-frame)
#+end_src
** Window margins
#+begin_src elisp
(setq-default left-margin-width 2 right-margin-width 0)
#+end_src
** Smooth scroll
Specific to Yamamoto Mitsuharu's port https://bitbucket.org/mituharu/emacs-mac/src/master/README-mac
#+begin_src elisp
(setq mac-mouse-wheel-smooth-scroll t)
#+end_src
** Visual line mode everywhere
Use global-visual-line-mode by default so that jk does not go up/down based on logical lines. Taken from [[https://emacs.stackexchange.com/questions/33360/how-to-open-org-files-with-visual-line-mode-automatically-turned-on][stackexchange]]. The goal here is to get vim-like behaviour of `nnoremap j gj` and `nnoremap k gk` in emacs.
#+begin_src elisp
(add-hook 'after-init-hook 'global-visual-line-mode)
#+end_src
** Line numbers
#+begin_src elisp
;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type nil)
#+end_src
** Prevent "jk" from exiting insert mode
#+begin_src elisp
(setq evil-escape-key-sequence nil)
#+end_src
** Prevent d/c/x from yanking
Found [[https://emacs.stackexchange.com/questions/23923/change-dd-command-in-evil-mode-to-not-write-to-clipboard][here]].
#+begin_src elisp
;; (defun my/evil-delete-advice (orig-fn beg end &optional type _ &rest args)
;;     "Make d, c, x to not write to clipboard."
;;     (apply orig-fn beg end type ?_ args))
;; (advice-add 'evil-delete :around 'my/evil-delete-advice)
;; (advice-add 'evil-change :around 'my/evil-delete-advice)
#+end_src
** Window management

Use "C-hjkl" for moving left/down/up/right
#+begin_src elisp
(bind-keys* ("C-h" . evil-window-left)
            ("C-j" . evil-window-down)
            ("C-k" . evil-window-up)
            ("C-l" . evil-window-right))
#+end_src

Use "C-c l" and "C-c j" for splitting windows vertically (right) and horizontally (down)
#+begin_src elisp
(bind-keys* ("C-c l" . evil-window-vsplit))
(bind-keys* ("C-c j" . evil-window-split))
#+end_src

Switch to the new window after splitting
#+begin_src elisp
(setq evil-split-window-below t
      evil-vsplit-window-right t)
#+end_src

Fullscreen/maximized mode toggle
#+begin_src elisp
(bind-key "C-c F" 'toggle-frame-maximized)
#+end_src

Kill buffer and window
#+begin_src elisp
;; C-c c will contain all buffer-related bindings
(global-set-key (kbd "C-c b") 'my/buffer)

(defalias 'my/buffer
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "k") 'kill-buffer-and-window)
    map) "Buffer-related bindings")
#+end_src

** Files/folders
This code block contains generality for "C-c f" as a "files" binding but it's currently not needed. Might come in handy later though.
#+begin_src elisp
;; "C-c f" for files/folders
;; (global-set-key (kbd "C-c f") 'my/files)

;; (defalias 'my/files
;;   (let ((map (make-sparse-keymap)))
;;     (define-key map (kbd "t") 'my/treemacs)
;;     map) "Files-related bindings")
#+end_src
*** Treemacs
#+begin_src elisp
;; "C-c f" for "files" and "folders"
(global-set-key (kbd "C-c f") 'my/treemacs)

(defalias 'my/treemacs
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "t") 'treemacs) ;; Toggle treemacs
    (define-key map (kbd "a") 'treemacs-add-project-to-workspace)
    (define-key map (kbd "r") 'treemacs-remove-project-from-workspace)
    map) "Treemacs-related bindings")
#+end_src
* Major mode-specific custom keybindings
Denote "C-c m" my/<localleader>, following Doom's naming of "SPC m".
#+begin_src elisp
(global-set-key (kbd "C-c m") 'my/<localleader>)
#+end_src
** Coding
*** Python
#+begin_src elisp
(defun my/bind-python-keys ()
  (defalias 'my/<localleader>
    (let ((map (make-sparse-keymap)))
      ;; REPL
      (define-key map (kbd "R") #'run-python)
      ;; Restart python
      (define-key map (kbd "r") #'pyvenv-restart-python)
      ;; Virtual environment
      (define-key map (kbd "v") #'pyvenv-activate)
      ;; Format
      (define-key map (kbd "f") #'+format/buffer)
      ;; LSP-related bindings
      (define-key map (kbd "l") #'my/lsp)
      ;; Jupyter-related bindings
      (define-key map (kbd "j") #'my/jupyter)
      map)))

(add-hook 'python-mode-hook 'my/bind-python-keys)
#+end_src

LSP bindings
#+begin_src elisp
(defun my/bind-python-lsp-keys ()
  (defalias 'my/lsp
    (let ((map (make-sparse-keymap)))
      ;; Restart lsp server
      (define-key map (kbd "r") #'lsp-workspace-restart)
      ;; Find definition
      (define-key map (kbd "f") #'lsp-find-definition)
      map)))

#+end_src

Add Python+LSP bindings on python-mode and lsp-mode hooks
#+begin_src elisp
(add-hook 'python-mode-hook
          '(lambda ()
             (add-hook 'lsp-mode-hook
                       #'my/bind-python-lsp-keys)))

#+end_src

Jupyter bindings
#+begin_src elisp
(defun my/bind-python-jupyter-keys ()
  (defalias 'my/jupyter
    (let ((map (make-sparse-keymap)))
      ;; Run jupyter REPL associated with current buffer
      (define-key map (kbd "R") #'jupyter-repl-associate-buffer)
      ;; Restart jupyter REPL
      (define-key map (kbd "r") #'jupyter-repl-restart-kernel)
      map)))

(add-hook 'python-mode-hook #'my/bind-python-jupyter-keys)

#+end_src

*** R
#+begin_src elisp
(defun my/bind-ess-r-keys ()
  (defalias 'my/<localleader>
    (let ((map (make-sparse-keymap)))
      ;; REPL
      (define-key map (kbd "R") #'run-ess-r)
      map)))

(add-hook 'ess-r-mode-hook 'my/bind-ess-r-keys)
#+end_src
** Writing
*** Spellcheck
#+begin_src elisp
(global-set-key (kbd "C-c s") 'my/spelling)

(defun my/bind-spell-fu-bindings ()
  (defalias 'my/spelling
    (let ((map (make-sparse-keymap)))
      ;; Add word to dictionary
      (define-key map (kbd "a") #'spell-fu-word-add)
      map)))

(add-hook 'spell-fu-mode-hook 'my/bind-spell-fu-bindings)
#+end_src
*** TeX
#+begin_src elisp
(defun my/latexmk ()
  (interactive)
  (TeX-command "LatexMk" #'TeX-master-file nil))

(defun my/bibtex ()
  (interactive)
  (TeX-command "BibTeX" #'TeX-master-file nil))

(defun my/latex-view ()
    (interactive)
  (TeX-command "View" #'TeX-master-file nil))

(defun my/bind-latex-keys ()
  (defalias 'my/<localleader>
    (let ((map (make-sparse-keymap)))
      ;; Compile
      (define-key map (kbd "c") #'my/latexmk)
      ;; Recompile BibTeX
      (define-key map (kbd "b") #'my/bibtex)
      ;; Word count
      (define-key map (kbd "w") #'tex-count-words)
      map)))

(add-hook 'LaTeX-mode-hook 'my/bind-latex-keys)
#+end_src
*** Markdown
#+begin_src elisp
(defun my/bind-markdown-keys ()
  (defalias 'my/<localleader>
    (let ((map (make-sparse-keymap)))
      ;; Format markdown table
      (define-key map (kbd "f") #'markdown-table-align)
      ;; Refresh toc
      (define-key map (kbd "r") #'markdown-toc-refresh-toc)
      map)))

(add-hook 'markdown-mode-hook 'my/bind-markdown-keys)
#+end_src
* Coding
** Python
Make LSP ignore virtual environments which satisfy the pattern "venv_*"
#+begin_src elisp
(defun my/python-lsp-ignore-venv ()
  (add-to-list 'lsp-file-watch-ignored "[/\\\\]\\venv_*"))
(add-hook 'python-mode-hook
          '(lambda () (add-hook 'lsp-mode-hook 'my/python-lsp-ignore-venv)))


#+end_src

Search for any virtual environments with pattern "venv_*" and if there's a unique match, automatically activate it.
#+begin_src elisp
(defun my/venv_pattern ()
  "User-customizable virtual environment pattern"
  "venv_*")

(defun my/get-matching-project-root-files (regexp)
  "Find all root directories/files that begin with `regexp`"
  (seq-filter
   (lambda (x) (equal 0 (string-match-p regexp x)))
   (directory-files (projectile-project-root))))

(defun my/python-venv-auto-activate ()
  "Activate the virtual environment satisfying the pattern given by the function, my/venv_pattern if it's a unique match, otherwise do nothing"
  (interactive)
  (setq matching-venvs (my/get-matching-project-root-files (my/venv_pattern)))
  ;; If there's a unique match, set the venv. Otherwise, do nothing
  (when (equal (length matching-venvs) 1)
    (pyvenv-activate (concat (projectile-project-root) (car matching-venvs)))))

(add-hook 'python-mode-hook 'my/python-venv-auto-activate)
#+end_src

*** Jupyter REPL
This allows sending code from a buffer straight to the REPL
#+begin_src elisp
(add-hook 'jupyter-repl-mode-hook (lambda () (setq jupyter-repl-echo-eval-p t)))
#+end_src
* LaTeX
Format environment and LatexMk on save
#+begin_src elisp

(defun my/latex-format-environment-on-save ()
  (add-hook 'after-save-hook #'LaTeX-fill-environment))

(defun my/latexmk-on-save ()
  "Run LatexMk after saving .tex files"
  (add-hook 'after-save-hook 'my/latexmk))

(add-hook 'LaTeX-mode-hook 'my/latexmk-on-save)
#+end_src

Make AUCTeX ask for main tex file in multi-document structure
#+begin_src elisp
(setq-default TeX-master nil)
#+end_src

Prevent AUCTeX from inserting braces automatically
#+begin_src elisp
(setq TeX-electric-sub-and-superscript nil)
#+end_src


Disable git-gutter when writing latex. Git-gutter seems to slow things down, and isn't necessary for me when writing latex.
Code obtained [[https://github.com/hlissner/doom-emacs/issues/1482][from here]].
#+begin_src elisp
(after! git-gutter
  (setq git-gutter:disabled-modes '(latex-mode)))
#+end_src

Other
#+begin_src elisp
;; Make default latex viewer pdf-tools
;; (setq +latex-viewers '(pdf-tools))

;; Use pdf-tools to open PDF files
;; (setq TeX-view-program-selection '((output-pdf "PDF Tools"))
;;       TeX-source-correlate-start-server t)

;; Update PDF buffers after successful LaTeX runs
;; (add-hook 'TeX-after-compilation-finished-functions
;;           #'TeX-revert-document-buffer)

;; ;; Disable smartparens auto double-quoting in latex (https://emacs.stackexchange.com/questions/52233/disable-tex-modes-auto-tex-insert-quote-functionaliy)
;; ;; Uncommented because it was causing issues with org fancy priority. Might need to revisit.
;; (map! :after tex
;;       :map TeX-mode-map
;;       "\"" nil)
;; (after! smartparens-latex
;;   (sp-local-pair '(tex-mode plain-tex-mode latex-mode LaTeX-mode)
;;                   "``" "''" :actions :rem))
#+end_src

* Org-mode

This directory allows syncing with beorg on iOS. Pretty cool!
#+begin_src elisp
(setq
 org-directory
 "~/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/")
#+end_src

Define a function for quickly opening up a file in the org directory
#+begin_src elisp
(defun my/open-org-directory ()
  (interactive) (ido-find-file-in-dir org-directory))

(global-set-key (kbd "C-c o") 'my/open-org-directory)
#+end_src

Make the first level org heading a little larger.
#+begin_src elisp
(custom-set-faces '(org-level-1 ((t (:inherit outline-1 :height 1.2)))))
#+end_src

Enable org-download so that we can drag and drop screenshots into org.
#+begin_src elisp
(require 'org-download)
(add-hook 'dired-mode-hook 'org-download-enable)
#+end_src

Use custom todo keywords and colours.
#+begin_src elisp
(after! org
  (setq org-todo-keywords
        '((sequence "IN-PROGRESS(p)" "TODO(t)" "WAITING(w)"
                    "IDEA(i)" "|" "DONE" "CANCELLED(c)"))))

;; Set other todo colors according to the nord theme (https://www.nordtheme.com/)
(setq org-todo-keyword-faces
      '(("IN-PROGRESS" . "#88C0D0")
        ("WAITING" . "#5E81AC")
        ("IDEA" . "#EBCB8B")
        ("CANCELED" . "#BF616A"))
      )

(setq org-log-done 'time)
#+end_src

Turn off org-superstar-mode
#+begin_src elisp
(remove-hook 'org-mode-hook #'org-superstar-mode)
#+end_src

Turn off org's eye candy
#+begin_src elisp
;; (after! org
;;   (setq org-fontify-quote-and-verse-blocks nil
;;         org-fontify-whole-heading-line nil
;;         org-hide-leading-stars nil
;;         org-startup-indented nil))
#+end_src

* Config management
Opening config.org, config.el, init.el, and packages.el uses "C-c e <char>" with <char> replaced by c, C, i, or p, respectively.
#+begin_src elisp

(defun my/goto-private-config-org-file ()
  "Open your private config.org file."
  (interactive)
  (find-file (expand-file-name "config.org" doom-private-dir)))

(defun my/goto-private-config-file ()
  "Open your private config.el file."
  (interactive)
  (find-file (expand-file-name "config.el" doom-private-dir)))

(defun my/goto-private-init-file ()
  "Open your private init.el file."
  (interactive)
  (find-file (expand-file-name "init.el" doom-private-dir)))

(defun my/goto-private-packages-file ()
  "Open your private packages.el file."
  (interactive)
  (find-file (expand-file-name "packages.el" doom-private-dir)))

;; C-c c will contain all config-related stuff
(global-set-key (kbd "C-c e") 'my/emacs-config)

(defalias 'my/emacs-config
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "c") #'my/goto-private-config-org-file)
    (define-key map (kbd "C") #'my/goto-private-config-file)
    (define-key map (kbd "i") #'my/goto-private-init-file)
    (define-key map (kbd "p") #'my/goto-private-packages-file)
    map) "Config-related bindings")
#+end_src
* Fonts
#+begin_src elisp
;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))
(setq doom-font (font-spec :family "Fira Mono" :size 15))
(setq doom-variable-pitch-font (font-spec :family "Fira Mono" :size 15))
#+end_src
* Theme
#+begin_src elisp
;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-nord)
#+end_src
* Misc
#+begin_src elisp

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "Ian Waudby-Smith"
      user-mail-address "iwaudbysmith@gmail.com")

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
#+end_src
** Autocomplete/company
#+begin_src elisp
;; Make autocomplete less clunky: https://github.com/hlissner/doom-emacs/issues/77
;; (require 'company)
;; (setq company-idle-delay 0.2
;;       company-minimum-prefix-length 4)
#+end_src
