#+TITLE: Doom Emacs config

Emacs config, requires [[https://github.com/hlissner/doom-emacs][Doom Emacs]].

This config is written as an org file ([[./config.el][config.el]]) and auto-compiles to [[./config.el][config.el]] using the ":config literate" option in [[./init.el][init.el]].

* Startup
#+begin_src elisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Make emacs maximized one startup
(add-hook 'doom-init-ui-hook 'toggle-frame-maximized)

;; Might be useful in the future: https://christiantietze.de/posts/2021/06/emacs-center-window-on-current-monitor/

#+end_src
* Navigation
** Visual line mode everywhere
Use global-visual-line-mode by default so that jk does not go up/down based on logical lines. Taken from [[https://emacs.stackexchange.com/questions/33360/how-to-open-org-files-with-visual-line-mode-automatically-turned-on][stackexchange]]. The goal here is to get vim-like behaviour of `nnoremap j gj` and `nnoremap k gk` in emacs.
#+begin_src elisp
(add-hook 'after-init-hook 'global-visual-line-mode)
#+end_src
** Line numbers
#+begin_src elisp
;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
;; (setq display-line-numbers-type 'nil)
#+end_src
** Prevent "jk" from exiting insert mode
#+begin_src elisp
(setq evil-escape-key-sequence nil)
#+end_src
** Window management

Switch to the new window after splitting
#+begin_src elisp
(setq evil-split-window-below t
      evil-vsplit-window-right t)

#+end_src

Fullscreen/maximized mode toggle
#+begin_src elisp
(bind-key "C-c F" 'toggle-frame-maximized)
#+end_src

Kill buffer and window
#+begin_src elisp
;; C-c c will contain all buffer-related bindings
(global-set-key (kbd "C-c b") 'my/buffer)

(defalias 'my/buffer
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "k") 'kill-buffer-and-window)
    map) "Buffer-related bindings")
#+end_src

** Files/folders
#+begin_src elisp
;; "C-c f" for files/folders
(global-set-key (kbd "C-c f") 'my/files)

(defalias 'my/files
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "t") 'my/treemacs)
    map) "Files-related bindings")
#+end_src
*** Treemacs
#+begin_src elisp
(defalias 'my/treemacs
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "t") 'treemacs) ;; Toggle treemacs
    (define-key map (kbd "a") 'treemacs-add-project-to-workspace)
    (define-key map (kbd "r") 'treemacs-remove-project-from-workspace)
    map) "Treemacs-related bindings")
#+end_src
* Coding
#+begin_src elisp
;; C-c c will contain all coding-related bindings
(global-set-key (kbd "C-c c") 'my/coding)

(defalias 'my/coding
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "p") 'my/python)
    (define-key map (kbd "r") 'my/r)
    (define-key map (kbd "c") 'my/cpp)
    (define-key map (kbd "j") 'my/julia)
    (define-key map (kbd "h") 'my/haskell)
    map) "Coding-related bindings")
#+end_src

** Python
#+begin_src elisp
(defalias 'my/python
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "r") #'run-python)
    (define-key map (kbd "v") #'pyvenv-activate)
    (define-key map (kbd "f") #'python-black-buffer)
    map) "Python-related bindings")
#+end_src

* Writing
#+begin_src elisp
;; C-c w will contain all writing-related bindings
(global-set-key (kbd "C-c w") 'my/writing)

(defalias 'my/writing
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "t") 'my/tex)
    (define-key map (kbd "o") 'my/org-mode)
    map) "Writing-related bindings")
#+end_src
** TeX
Add TeX-related bindings
#+begin_src elisp
(defalias 'my/tex
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "c") 'tex-count-words)
    map))
#+end_src

Other settings
#+begin_src elisp
;; Make default latex viewer pdf-tools
;; (setq +latex-viewers '(pdf-tools))

;; Use pdf-tools to open PDF files
(setq TeX-view-program-selection '((output-pdf "PDF Tools"))
      TeX-source-correlate-start-server t)

;; Update PDF buffers after successful LaTeX runs
(add-hook 'TeX-after-compilation-finished-functions
          #'TeX-revert-document-buffer)

;; Make AUCTeX ask for main tex file in multi-document structure
(setq-default TeX-master nil)

;; Prevent AUCTeX from inserting braces automatically
(setq TeX-electric-sub-and-superscript nil)
#+end_src
#+begin_src elisp
#+end_src

** Org-mode
Org-mode-related keybindings
#+begin_src elisp
;; Quickly open up a file in the org directory
(defun my/open-org-directory ()
  (interactive) (ido-find-file-in-dir org-directory))

(defalias 'my/org-mode
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "o") 'my/open-org-directory)
    map))
#+end_src

This directory allows syncing with beorg on iOS. Pretty cool!
#+begin_src elisp
(setq
 org-directory
 "~/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/")

#+end_src
Make the first level org heading a little larger.
#+begin_src elisp
(custom-set-faces '(org-level-1 ((t (:inherit outline-1 :height 1.2)))))
#+end_src

Enable org-download so that we can drag and drop screenshots into org.
#+begin_src elisp
(require 'org-download)
(add-hook 'dired-mode-hook 'org-download-enable)
#+end_src

Use custom todo keywords and colours.
#+begin_src elisp
(after! org
  (setq org-todo-keywords
        '((sequence "TODO(t)" "IN-PROGRESS(p)" "WAITING(w)"
                    "IDEA(i)" "|" "DONE" "CANCELLED(c)"))))

;; Set other todo colors according to the nord theme (https://www.nordtheme.com/)
(setq org-todo-keyword-faces
      '(("IN-PROGRESS" . "#88C0D0")
        ("WAITING" . "#5E81AC")
        ("IDEA" . "#EBCB8B")
        ("CANCELED" . "#BF616A"))
      )

(setq org-log-done 'time)
#+end_src
* Shells
#+begin_src elisp
;; C-c s will contain all shell-related commands
(global-set-key (kbd "C-c s") 'my/shells)

(defalias 'my/shells
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "s") 'shell)
    (define-key map (kbd "e") 'eshell)
    (define-key map (kbd "t") 'term)
    (define-key map (kbd "v") 'vterm)
    map) "Shell-related bindings")
#+end_src
* Config management
Opening config.org, config.el, init.el, and packages.el uses "C-c e <char>" with <char> replaced by c, C, i, or p, respectively.
#+begin_src elisp

(defun my/goto-private-config-org-file ()
  "Open your private config.org file."
  (interactive)
  (find-file (expand-file-name "config.org" doom-private-dir)))

(defun my/goto-private-config-file ()
  "Open your private config.el file."
  (interactive)
  (find-file (expand-file-name "config.el" doom-private-dir)))

(defun my/goto-private-init-file ()
  "Open your private init.el file."
  (interactive)
  (find-file (expand-file-name "init.el" doom-private-dir)))

(defun my/goto-private-packages-file ()
  "Open your private packages.el file."
  (interactive)
  (find-file (expand-file-name "packages.el" doom-private-dir)))

;; C-c c will contain all config-related stuff
(global-set-key (kbd "C-c e") 'my/emacs-config)

(defalias 'my/emacs-config
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "c") #'my/goto-private-config-org-file)
    (define-key map (kbd "C") #'my/goto-private-config-file)
    (define-key map (kbd "i") #'my/goto-private-init-file)
    (define-key map (kbd "p") #'my/goto-private-packages-file)
    map) "Config-related bindings")
#+end_src
* Fonts
#+begin_src elisp
;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))
(setq doom-font (font-spec :family "Fira Mono" :size 15))
(setq doom-variable-pitch-font (font-spec :family "Fira Mono" :size 15))
(setq +zen-text-scale 0.25)
#+end_src
* Theme
#+begin_src elisp
;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-nord)
#+end_src
* Misc
#+begin_src elisp

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "Ian Waudby-Smith"
      user-mail-address "iwaudbysmith@gmail.com")

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
#+end_src
** Autocomplete/company
#+begin_src elisp
;; Make autocomplete less clunky: https://github.com/hlissner/doom-emacs/issues/77
;; (require 'company)
;; (setq company-idle-delay 0.2
;;       company-minimum-prefix-length 4)
#+end_src

